# Generated by Django 6.0.3 on 2026-04-16 18:49

import django.db.models.deletion
import estoque.upload_paths
from django.db import migrations, models


def _pg_index_visible(cursor, name: str) -> bool:
    cursor.execute(
        """
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind = 'i' AND c.relname = %s
          AND pg_catalog.pg_table_is_visible(c.oid)
        """,
        [name],
    )
    return cursor.fetchone() is not None


def _sync_renamed_indexes_forward(apps, schema_editor):
    """Renomeia índices legados; se o nome antigo não existir, cria o novo (BD fora de sync)."""
    connection = schema_editor.connection
    if connection.vendor != 'postgresql':
        return
    qn = connection.ops.quote_name
    specs = [
        (
            'idx_cautela_empresa_situacao',
            'estoque_cau_empresa_a00dac_idx',
            'CREATE INDEX {} ON estoque_cautela (empresa_id, situacao)',
        ),
        (
            'idx_cautela_empresa_entrega',
            'estoque_cau_empresa_690f64_idx',
            'CREATE INDEX {} ON estoque_cautela (empresa_id, entrega)',
        ),
        (
            'estoque_req_empresa_criado',
            'estoque_req_empresa_5d1e02_idx',
            'CREATE INDEX {} ON estoque_requisicaoestoque (empresa_id, criado_em)',
        ),
        (
            'estoque_req_emp_st_cri_idx',
            'estoque_req_empresa_65258e_idx',
            'CREATE INDEX {} ON estoque_requisicaoestoque (empresa_id, status, criado_em)',
        ),
    ]
    with connection.cursor() as cursor:
        for old, new, create_sql in specs:
            if _pg_index_visible(cursor, new):
                continue
            if _pg_index_visible(cursor, old):
                cursor.execute(
                    'ALTER INDEX {} RENAME TO {}'.format(qn(old), qn(new))
                )
            else:
                cursor.execute(create_sql.format(qn(new)))


def _sync_renamed_indexes_backward(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor != 'postgresql':
        return
    qn = connection.ops.quote_name
    pairs = [
        ('estoque_cau_empresa_a00dac_idx', 'idx_cautela_empresa_situacao'),
        ('estoque_cau_empresa_690f64_idx', 'idx_cautela_empresa_entrega'),
        ('estoque_req_empresa_5d1e02_idx', 'estoque_req_empresa_criado'),
        ('estoque_req_empresa_65258e_idx', 'estoque_req_emp_st_cri_idx'),
    ]
    with connection.cursor() as cursor:
        for new, old in pairs:
            if _pg_index_visible(cursor, old):
                continue
            if _pg_index_visible(cursor, new):
                cursor.execute(
                    'ALTER INDEX {} RENAME TO {}'.format(qn(new), qn(old))
                )


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_alter_empresa_endereco'),
        ('estoque', '0011_rascunhonovacautela'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoDevolucaoCautela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Motivo da devolução (cautela)',
                'verbose_name_plural': 'Motivos da devolução (cautela)',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SituacaoFerramentasPosDevolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Situação da(s) ferramentas (pós-devolução)',
                'verbose_name_plural': 'Situações da(s) ferramentas (pós-devolução)',
                'ordering': ['nome'],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    _sync_renamed_indexes_forward,
                    _sync_renamed_indexes_backward,
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='cautela',
                    new_name='estoque_cau_empresa_a00dac_idx',
                    old_name='idx_cautela_empresa_situacao',
                ),
                migrations.RenameIndex(
                    model_name='cautela',
                    new_name='estoque_cau_empresa_690f64_idx',
                    old_name='idx_cautela_empresa_entrega',
                ),
                migrations.RenameIndex(
                    model_name='requisicaoestoque',
                    new_name='estoque_req_empresa_5d1e02_idx',
                    old_name='estoque_req_empresa_criado',
                ),
                migrations.RenameIndex(
                    model_name='requisicaoestoque',
                    new_name='estoque_req_empresa_65258e_idx',
                    old_name='estoque_req_emp_st_cri_idx',
                ),
            ],
        ),
        migrations.AddField(
            model_name='entrega_cautela',
            name='ferramentas_devolvidas',
            field=models.ManyToManyField(blank=True, related_name='entregas_cautela_devolucoes', to='estoque.ferramenta', verbose_name='Ferramentas devolvidas neste registro'),
        ),
        migrations.AlterField(
            model_name='item',
            name='qrcode_imagem',
            field=models.ImageField(blank=True, help_text='Imagem do QR Code gerada ao salvar o item (leitor 2D nas telas de estoque).', null=True, upload_to=estoque.upload_paths.item_qrcode_upload, verbose_name='QR Code'),
        ),
        migrations.AddField(
            model_name='motivodevolucaocautela',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivos_devolucao_cautela', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='entrega_cautela',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas_cautela', to='estoque.motivodevolucaocautela'),
        ),
        migrations.AddField(
            model_name='situacaoferramentasposdevolucao',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situacoes_ferramentas_pos_devolucao', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='entrega_cautela',
            name='situacao_ferramentas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas_cautela', to='estoque.situacaoferramentasposdevolucao', verbose_name='Situação da(s) ferramentas'),
        ),
        migrations.AddConstraint(
            model_name='motivodevolucaocautela',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='uniq_motivo_devolucao_cautela_empresa_nome'),
        ),
        migrations.AddConstraint(
            model_name='situacaoferramentasposdevolucao',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='uniq_situacao_ferr_pos_dev_empresa_nome'),
        ),
    ]
