# Generated by Django 6.0.3 on 2026-05-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0016_listacompraestoque_nome'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listacompraestoque',
            new_name='estoque_lis_empresa_03266d_idx',
            old_name='estoque_lis_empresa_16e0f3_idx',
        ),
        migrations.RenameIndex(
            model_name='listacompraestoque',
            new_name='estoque_lis_empresa_2e897a_idx',
            old_name='estoque_lis_empresa_0a3f7d_idx',
        ),
    ]
