# Generated by Django 6.0.3 on 2026-07-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0017_rename_estoque_lis_empresa_16e0f3_idx_estoque_lis_empresa_03266d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramenta',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade cadastrada desta ferramenta.', verbose_name='Quantidade'),
        ),
    ]
