# Generated by Django 6.0.3 on 2026-07-23 13:05

import django.db.models.deletion
from django.db import migrations, models


def popular_quantidades_cautelas(apps, schema_editor):
    Cautela = apps.get_model('estoque', 'Cautela')
    CautelaFerramentaQuantidade = apps.get_model(
        'estoque', 'CautelaFerramentaQuantidade'
    )
    rows = []
    for cautela in Cautela.objects.prefetch_related('ferramentas').iterator(chunk_size=200):
        for ferramenta in cautela.ferramentas.all():
            rows.append(
                CautelaFerramentaQuantidade(
                    cautela_id=cautela.pk,
                    ferramenta_id=ferramenta.pk,
                    quantidade=1,
                )
            )
    if rows:
        CautelaFerramentaQuantidade.objects.bulk_create(rows, ignore_conflicts=True)


def remover_quantidades_cautelas(apps, schema_editor):
    CautelaFerramentaQuantidade = apps.get_model(
        'estoque', 'CautelaFerramentaQuantidade'
    )
    CautelaFerramentaQuantidade.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0018_ferramenta_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='CautelaFerramentaQuantidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('cautela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferramentas_quantidades', to='estoque.cautela')),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cautelas_quantidades', to='estoque.ferramenta')),
            ],
            options={
                'verbose_name': 'Quantidade de ferramenta na cautela',
                'verbose_name_plural': 'Quantidades de ferramentas na cautela',
                'ordering': ['ferramenta__descricao', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('cautela', 'ferramenta'), name='uniq_cautela_ferramenta_quantidade')],
            },
        ),
        migrations.RunPython(
            popular_quantidades_cautelas,
            remover_quantidades_cautelas,
        ),
    ]
