from django.urls import path

from core.view_helpers import empresa_scoped

from . import item_views, requisicoes_views, views


app_name = 'estoque'

urlpatterns = [
    path('', empresa_scoped(views.dashboard), name='dashboard'),
    path('requisicoes/', empresa_scoped(requisicoes_views.lista_requisicoes), name='requisicoes'),
    path(
        'requisicoes/<int:pk>/',
        empresa_scoped(requisicoes_views.detalhe_requisicao),
        name='detalhe_requisicao',
    ),
    path(
        'requisicoes/<int:pk>/editar/',
        empresa_scoped(requisicoes_views.editar_requisicao),
        name='editar_requisicao',
    ),
    path(
        'requisicoes/<int:pk>/imprimir/',
        empresa_scoped(requisicoes_views.imprimir_requisicao),
        name='imprimir_requisicao',
    ),
    path(
        'requisicoes/<int:pk>/imprimir/pdf/',
        empresa_scoped(requisicoes_views.imprimir_requisicao_pdf),
        name='imprimir_requisicao_pdf',
    ),
    path(
        'requisicoes/<int:pk>/cancelar/',
        empresa_scoped(requisicoes_views.cancelar_requisicao),
        name='cancelar_requisicao',
    ),
    path(
        'requisicoes/<int:pk>/excluir/',
        empresa_scoped(requisicoes_views.cancelar_requisicao),
        name='excluir_requisicao',
    ),
    path(
        'requisicoes/modal/<int:pk>/itens/',
        empresa_scoped(requisicoes_views.modal_requisicao_itens),
        name='modal_requisicao_itens',
    ),
    path('requisicoes/nova/', empresa_scoped(requisicoes_views.nova_requisicao), name='nova_requisicao'),
    path(
        'requisicoes/modal/buscar-itens/',
        empresa_scoped(requisicoes_views.modal_buscar_itens_requisicao),
        name='modal_buscar_itens_requisicao',
    ),
    path(
        'requisicoes/partial/buscar-itens/',
        empresa_scoped(requisicoes_views.partial_buscar_itens_requisicao),
        name='partial_buscar_itens_requisicao',
    ),
    path(
        'requisicoes/modal/item/<int:pk>/',
        empresa_scoped(requisicoes_views.modal_editar_item_requisicao),
        name='modal_editar_item_requisicao',
    ),
    path(
        'requisicoes/modal/item/<int:pk>/devolver/',
        empresa_scoped(requisicoes_views.devolver_item_requisicao),
        name='devolver_item_requisicao',
    ),
    path(
        'requisicoes/autocomplete/solicitantes/',
        empresa_scoped(requisicoes_views.autocomplete_solicitantes),
        name='autocomplete_solicitantes',
    ),
    path(
        'requisicoes/autocomplete/locais/',
        empresa_scoped(requisicoes_views.autocomplete_locais),
        name='autocomplete_locais',
    ),
    path(
        'requisicoes/autocomplete/obras/',
        empresa_scoped(requisicoes_views.autocomplete_obras),
        name='autocomplete_obras',
    ),
    path(
        'movimentar/',
        empresa_scoped(item_views.movimentar_estoque),
        name='movimentar_estoque',
    ),
    path(
        'todo/',
        empresa_scoped(item_views.todo_estoque),
        name='todo_estoque',
    ),
    path(
        'leitor/resolve/',
        empresa_scoped(item_views.leitor_estoque_resolve),
        name='leitor_estoque_resolve',
    ),
    path(
        'categorias-itens/',
        empresa_scoped(views.lista_categorias_itens),
        name='lista_categorias_itens',
    ),
    path(
        'categorias-itens/modal/novo/',
        empresa_scoped(views.modal_novo_categoria_item),
        name='modal_novo_categoria_item',
    ),
    path(
        'categorias-itens/modal/<int:pk>/excluir/',
        empresa_scoped(views.modal_excluir_categoria_item),
        name='modal_excluir_categoria_item',
    ),
    path(
        'categorias-itens/modal/<int:pk>/',
        empresa_scoped(views.modal_editar_categoria_item),
        name='modal_editar_categoria_item',
    ),
    path(
        'categorias-itens/nova/',
        empresa_scoped(views.criar_categoria_item),
        name='criar_categoria_item',
    ),
    path(
        'categorias-itens/<int:pk>/editar/',
        empresa_scoped(views.editar_categoria_item),
        name='editar_categoria_item',
    ),
    path(
        'categorias-itens/<int:pk>/excluir/',
        empresa_scoped(views.excluir_categoria_item),
        name='excluir_categoria_item',
    ),
    path(
        'categorias-ferramentas/',
        empresa_scoped(views.lista_categorias_ferramentas),
        name='lista_categorias_ferramentas',
    ),
    path(
        'categorias-ferramentas/modal/novo/',
        empresa_scoped(views.modal_novo_categoria_ferramenta),
        name='modal_novo_categoria_ferramenta',
    ),
    path(
        'categorias-ferramentas/modal/<int:pk>/excluir/',
        empresa_scoped(views.modal_excluir_categoria_ferramenta),
        name='modal_excluir_categoria_ferramenta',
    ),
    path(
        'categorias-ferramentas/modal/<int:pk>/',
        empresa_scoped(views.modal_editar_categoria_ferramenta),
        name='modal_editar_categoria_ferramenta',
    ),
    path(
        'categorias-ferramentas/nova/',
        empresa_scoped(views.criar_categoria_ferramenta),
        name='criar_categoria_ferramenta',
    ),
    path(
        'categorias-ferramentas/<int:pk>/editar/',
        empresa_scoped(views.editar_categoria_ferramenta),
        name='editar_categoria_ferramenta',
    ),
    path(
        'categorias-ferramentas/<int:pk>/excluir/',
        empresa_scoped(views.excluir_categoria_ferramenta),
        name='excluir_categoria_ferramenta',
    ),
    path(
        'unidades-medida/',
        empresa_scoped(views.lista_unidades_medida),
        name='lista_unidades_medida',
    ),
    path(
        'unidades-medida/modal/novo/',
        empresa_scoped(views.modal_novo_unidade_medida),
        name='modal_novo_unidade_medida',
    ),
    path(
        'unidades-medida/modal/<int:pk>/excluir/',
        empresa_scoped(views.modal_excluir_unidade_medida),
        name='modal_excluir_unidade_medida',
    ),
    path(
        'unidades-medida/modal/<int:pk>/',
        empresa_scoped(views.modal_editar_unidade_medida),
        name='modal_editar_unidade_medida',
    ),
    path(
        'unidades-medida/nova/',
        empresa_scoped(views.criar_unidade_medida),
        name='criar_unidade_medida',
    ),
    path(
        'unidades-medida/<int:pk>/editar/',
        empresa_scoped(views.editar_unidade_medida),
        name='editar_unidade_medida',
    ),
    path(
        'unidades-medida/<int:pk>/excluir/',
        empresa_scoped(views.excluir_unidade_medida),
        name='excluir_unidade_medida',
    ),
    path('itens/', empresa_scoped(item_views.lista_itens), name='lista_itens'),
    path(
        'itens/modal/novo/',
        empresa_scoped(item_views.modal_novo_item),
        name='modal_novo_item',
    ),
    path(
        'itens/modal/<int:pk>/excluir/',
        empresa_scoped(item_views.modal_excluir_item),
        name='modal_excluir_item',
    ),
    path(
        'itens/modal/<int:pk>/gerar-qrcode/',
        empresa_scoped(item_views.modal_gerar_qrcode_item),
        name='modal_gerar_qrcode_item',
    ),
    path(
        'itens/modal/<int:pk>/excluir-qrcode/',
        empresa_scoped(item_views.modal_excluir_qrcode_item),
        name='modal_excluir_qrcode_item',
    ),
    path(
        'itens/modal/<int:pk>/',
        empresa_scoped(item_views.modal_editar_item),
        name='modal_editar_item',
    ),
    path(
        'itens/modal/<int:pk>/movimentar-saldo/',
        empresa_scoped(item_views.modal_movimentar_saldo),
        name='modal_movimentar_saldo',
    ),
    path('itens/novo/', empresa_scoped(item_views.item_novo), name='item_novo'),
    path(
        'itens/<int:item_pk>/imagens/<int:imagem_pk>/excluir/',
        empresa_scoped(item_views.item_imagem_excluir),
        name='item_imagem_excluir',
    ),
    path(
        'itens/<int:pk>/editar/',
        empresa_scoped(item_views.item_editar),
        name='item_editar',
    ),
    path(
        'itens/<int:pk>/excluir/',
        empresa_scoped(item_views.item_excluir),
        name='item_excluir',
    ),
]
