from django.urls import path

from core.view_helpers import empresa_scoped

from . import (
    cautela_views,
    ferramenta_views,
    item_views,
    relatorios_views,
    requisicoes_views,
    views,
)


app_name = 'estoque'

urlpatterns = [
    path('', empresa_scoped(views.dashboard), name='dashboard'),
    path(
        'partial/dashboard-cards/',
        empresa_scoped(views.partial_dashboard_cards),
        name='partial_dashboard_cards',
    ),
    path('requisicoes/', empresa_scoped(requisicoes_views.lista_requisicoes), name='requisicoes'),
    path(
        'requisicoes/<int:pk>/',
        empresa_scoped(requisicoes_views.detalhe_requisicao),
        name='detalhe_requisicao',
    ),
    path(
        'requisicoes/<int:pk>/editar/',
        empresa_scoped(requisicoes_views.editar_requisicao),
        name='editar_requisicao',
    ),
    path(
        'requisicoes/<int:pk>/imprimir/',
        empresa_scoped(requisicoes_views.imprimir_requisicao),
        name='imprimir_requisicao',
    ),
    path(
        'requisicoes/<int:pk>/imprimir/pdf/',
        empresa_scoped(requisicoes_views.imprimir_requisicao_pdf),
        name='imprimir_requisicao_pdf',
    ),
    path(
        'requisicoes/<int:pk>/cancelar/',
        empresa_scoped(requisicoes_views.cancelar_requisicao),
        name='cancelar_requisicao',
    ),
    path(
        'requisicoes/<int:pk>/excluir/',
        empresa_scoped(requisicoes_views.cancelar_requisicao),
        name='excluir_requisicao',
    ),
    path(
        'requisicoes/modal/<int:pk>/itens/',
        empresa_scoped(requisicoes_views.modal_requisicao_itens),
        name='modal_requisicao_itens',
    ),
    path('requisicoes/nova/', empresa_scoped(requisicoes_views.nova_requisicao), name='nova_requisicao'),
    path(
        'requisicoes/modal/buscar-itens/',
        empresa_scoped(requisicoes_views.modal_buscar_itens_requisicao),
        name='modal_buscar_itens_requisicao',
    ),
    path(
        'requisicoes/partial/buscar-itens/',
        empresa_scoped(requisicoes_views.partial_buscar_itens_requisicao),
        name='partial_buscar_itens_requisicao',
    ),
    path(
        'requisicoes/modal/item/<int:pk>/',
        empresa_scoped(requisicoes_views.modal_editar_item_requisicao),
        name='modal_editar_item_requisicao',
    ),
    path(
        'requisicoes/modal/item/<int:pk>/devolver/',
        empresa_scoped(requisicoes_views.devolver_item_requisicao),
        name='devolver_item_requisicao',
    ),
    path(
        'requisicoes/autocomplete/solicitantes/',
        empresa_scoped(requisicoes_views.autocomplete_solicitantes),
        name='autocomplete_solicitantes',
    ),
    path(
        'requisicoes/autocomplete/locais/',
        empresa_scoped(requisicoes_views.autocomplete_locais),
        name='autocomplete_locais',
    ),
    path(
        'requisicoes/autocomplete/obras/',
        empresa_scoped(requisicoes_views.autocomplete_obras),
        name='autocomplete_obras',
    ),
    path(
        'relatorios/impressao/pdf/',
        empresa_scoped(relatorios_views.relatorios_impressao_pdf),
        name='relatorios_impressao_pdf',
    ),
    path(
        'relatorios/impressao/',
        empresa_scoped(relatorios_views.relatorios_impressao),
        name='relatorios_impressao',
    ),
    path(
        'relatorios/',
        empresa_scoped(relatorios_views.relatorios_estoque),
        name='relatorios_estoque',
    ),
    path(
        'relatorios/autocomplete/funcionario/',
        empresa_scoped(relatorios_views.autocomplete_funcionarios_relatorio),
        name='autocomplete_funcionarios_relatorio',
    ),
    path(
        'relatorios/autocomplete/ferramenta/',
        empresa_scoped(relatorios_views.autocomplete_ferramentas_relatorio),
        name='autocomplete_ferramentas_relatorio',
    ),
    path(
        'relatorios/autocomplete/item/',
        empresa_scoped(relatorios_views.autocomplete_itens_relatorio),
        name='autocomplete_itens_relatorio',
    ),
    path(
        'movimentar/',
        empresa_scoped(item_views.movimentar_estoque),
        name='movimentar_estoque',
    ),
    path(
        'todo/',
        empresa_scoped(item_views.todo_estoque),
        name='todo_estoque',
    ),
    path(
        'leitor/resolve/',
        empresa_scoped(item_views.leitor_estoque_resolve),
        name='leitor_estoque_resolve',
    ),
    path(
        'categorias-itens/',
        empresa_scoped(views.lista_categorias_itens),
        name='lista_categorias_itens',
    ),
    path(
        'categorias-itens/modal/novo/',
        empresa_scoped(views.modal_novo_categoria_item),
        name='modal_novo_categoria_item',
    ),
    path(
        'categorias-itens/modal/<int:pk>/excluir/',
        empresa_scoped(views.modal_excluir_categoria_item),
        name='modal_excluir_categoria_item',
    ),
    path(
        'categorias-itens/modal/<int:pk>/',
        empresa_scoped(views.modal_editar_categoria_item),
        name='modal_editar_categoria_item',
    ),
    path(
        'categorias-itens/nova/',
        empresa_scoped(views.criar_categoria_item),
        name='criar_categoria_item',
    ),
    path(
        'categorias-itens/<int:pk>/editar/',
        empresa_scoped(views.editar_categoria_item),
        name='editar_categoria_item',
    ),
    path(
        'categorias-itens/<int:pk>/excluir/',
        empresa_scoped(views.excluir_categoria_item),
        name='excluir_categoria_item',
    ),
    path(
        'categorias-ferramentas/',
        empresa_scoped(views.lista_categorias_ferramentas),
        name='lista_categorias_ferramentas',
    ),
    path(
        'categorias-ferramentas/modal/novo/',
        empresa_scoped(views.modal_novo_categoria_ferramenta),
        name='modal_novo_categoria_ferramenta',
    ),
    path(
        'categorias-ferramentas/modal/<int:pk>/excluir/',
        empresa_scoped(views.modal_excluir_categoria_ferramenta),
        name='modal_excluir_categoria_ferramenta',
    ),
    path(
        'categorias-ferramentas/modal/<int:pk>/',
        empresa_scoped(views.modal_editar_categoria_ferramenta),
        name='modal_editar_categoria_ferramenta',
    ),
    path(
        'categorias-ferramentas/nova/',
        empresa_scoped(views.criar_categoria_ferramenta),
        name='criar_categoria_ferramenta',
    ),
    path(
        'categorias-ferramentas/<int:pk>/editar/',
        empresa_scoped(views.editar_categoria_ferramenta),
        name='editar_categoria_ferramenta',
    ),
    path(
        'categorias-ferramentas/<int:pk>/excluir/',
        empresa_scoped(views.excluir_categoria_ferramenta),
        name='excluir_categoria_ferramenta',
    ),
    path(
        'unidades-medida/',
        empresa_scoped(views.lista_unidades_medida),
        name='lista_unidades_medida',
    ),
    path(
        'unidades-medida/modal/novo/',
        empresa_scoped(views.modal_novo_unidade_medida),
        name='modal_novo_unidade_medida',
    ),
    path(
        'unidades-medida/modal/<int:pk>/excluir/',
        empresa_scoped(views.modal_excluir_unidade_medida),
        name='modal_excluir_unidade_medida',
    ),
    path(
        'unidades-medida/modal/<int:pk>/',
        empresa_scoped(views.modal_editar_unidade_medida),
        name='modal_editar_unidade_medida',
    ),
    path(
        'unidades-medida/nova/',
        empresa_scoped(views.criar_unidade_medida),
        name='criar_unidade_medida',
    ),
    path(
        'unidades-medida/<int:pk>/editar/',
        empresa_scoped(views.editar_unidade_medida),
        name='editar_unidade_medida',
    ),
    path(
        'unidades-medida/<int:pk>/excluir/',
        empresa_scoped(views.excluir_unidade_medida),
        name='excluir_unidade_medida',
    ),
    path(
        'ferramentas/',
        empresa_scoped(ferramenta_views.lista_ferramentas),
        name='lista_ferramentas',
    ),
    path(
        'ferramentas/cautela/',
        empresa_scoped(cautela_views.cautela_ferramentas),
        name='cautela_ferramentas',
    ),
    path(
        'ferramentas/cautela/nova/',
        empresa_scoped(cautela_views.nova_cautela),
        name='cautela_nova',
    ),
    path(
        'ferramentas/cautela/rascunho/',
        empresa_scoped(cautela_views.api_rascunho_nova_cautela),
        name='api_rascunho_nova_cautela',
    ),
    path(
        'ferramentas/cautela/<int:pk>/',
        empresa_scoped(cautela_views.detalhe_cautela),
        name='cautela_detalhe',
    ),
    path(
        'ferramentas/cautela/<int:pk>/editar/',
        empresa_scoped(cautela_views.editar_cautela_staff),
        name='cautela_editar_staff',
    ),
    path(
        'ferramentas/cautela/<int:pk>/excluir/',
        empresa_scoped(cautela_views.excluir_cautela_staff),
        name='cautela_excluir_staff',
    ),
    path(
        'ferramentas/cautela/<int:pk>/entrega/',
        empresa_scoped(cautela_views.modal_entrega_cautela),
        name='modal_entrega_cautela',
    ),
    path(
        'ferramentas/cautela/<int:pk>/adiar/',
        empresa_scoped(cautela_views.modal_adiar_cautela),
        name='modal_adiar_cautela',
    ),
    path(
        'ferramentas/cautela/modal/buscar-itens/',
        empresa_scoped(cautela_views.modal_buscar_itens_cautela),
        name='modal_buscar_itens_cautela',
    ),
    path(
        'ferramentas/cautela/partial/buscar-itens/',
        empresa_scoped(cautela_views.partial_buscar_itens_cautela),
        name='partial_buscar_itens_cautela',
    ),
    path(
        'ferramentas/modal/novo/',
        empresa_scoped(ferramenta_views.modal_novo_ferramenta),
        name='modal_novo_ferramenta',
    ),
    path(
        'ferramentas/modal/<int:pk>/excluir/',
        empresa_scoped(ferramenta_views.modal_excluir_ferramenta),
        name='modal_excluir_ferramenta',
    ),
    path(
        'ferramentas/modal/<int:pk>/gerar-qrcode/',
        empresa_scoped(ferramenta_views.modal_gerar_qrcode_ferramenta),
        name='modal_gerar_qrcode_ferramenta',
    ),
    path(
        'ferramentas/modal/<int:pk>/excluir-qrcode/',
        empresa_scoped(ferramenta_views.modal_excluir_qrcode_ferramenta),
        name='modal_excluir_qrcode_ferramenta',
    ),
    path(
        'ferramentas/modal/<int:pk>/',
        empresa_scoped(ferramenta_views.modal_editar_ferramenta),
        name='modal_editar_ferramenta',
    ),
    path(
        'ferramentas/novo/',
        empresa_scoped(ferramenta_views.ferramenta_novo),
        name='ferramenta_novo',
    ),
    path(
        'ferramentas/<int:pk>/etiqueta/pdf/',
        empresa_scoped(ferramenta_views.imprimir_etiqueta_ferramenta),
        name='imprimir_etiqueta_ferramenta',
    ),
    path(
        'ferramentas/<int:pk>/etiqueta/png/',
        empresa_scoped(ferramenta_views.imprimir_etiqueta_ferramenta_png),
        name='imprimir_etiqueta_ferramenta_png',
    ),
    path(
        'ferramentas/<int:pk>/modal/adicionar-imagens/',
        empresa_scoped(ferramenta_views.modal_adicionar_imagens_ferramenta),
        name='modal_adicionar_imagens_ferramenta',
    ),
    path(
        'ferramentas/<int:ferramenta_pk>/imagens/<int:imagem_pk>/excluir/',
        empresa_scoped(ferramenta_views.ferramenta_imagem_excluir),
        name='ferramenta_imagem_excluir',
    ),
    path(
        'ferramentas/<int:ferramenta_pk>/imagens/<int:imagem_pk>/padrao/',
        empresa_scoped(ferramenta_views.ferramenta_imagem_definir_padrao),
        name='ferramenta_imagem_definir_padrao',
    ),
    path(
        'ferramentas/<int:pk>/',
        empresa_scoped(ferramenta_views.detalhes_ferramenta),
        name='detalhes_ferramenta',
    ),
    path(
        'ferramentas/<int:pk>/editar/',
        empresa_scoped(ferramenta_views.ferramenta_editar),
        name='ferramenta_editar',
    ),
    path(
        'ferramentas/<int:pk>/excluir/',
        empresa_scoped(ferramenta_views.ferramenta_excluir),
        name='ferramenta_excluir',
    ),
    path('itens/', empresa_scoped(item_views.lista_itens), name='lista_itens'),
    path(
        'itens/modal/novo/',
        empresa_scoped(item_views.modal_novo_item),
        name='modal_novo_item',
    ),
    path(
        'itens/modal/<int:pk>/excluir/',
        empresa_scoped(item_views.modal_excluir_item),
        name='modal_excluir_item',
    ),
    path(
        'itens/modal/<int:pk>/gerar-qrcode/',
        empresa_scoped(item_views.modal_gerar_qrcode_item),
        name='modal_gerar_qrcode_item',
    ),
    path(
        'itens/modal/<int:pk>/excluir-qrcode/',
        empresa_scoped(item_views.modal_excluir_qrcode_item),
        name='modal_excluir_qrcode_item',
    ),
    path(
        'itens/modal/<int:pk>/',
        empresa_scoped(item_views.modal_editar_item),
        name='modal_editar_item',
    ),
    path(
        'itens/modal/<int:pk>/movimentar-saldo/',
        empresa_scoped(item_views.modal_movimentar_saldo),
        name='modal_movimentar_saldo',
    ),
    path(
        'itens/<int:pk>/modal/adicionar-imagens/',
        empresa_scoped(item_views.modal_adicionar_imagens_item),
        name='modal_adicionar_imagens_item',
    ),
    path('itens/novo/', empresa_scoped(item_views.item_novo), name='item_novo'),
    path(
        'itens/<int:item_pk>/imagens/<int:imagem_pk>/excluir/',
        empresa_scoped(item_views.item_imagem_excluir),
        name='item_imagem_excluir',
    ),
    path(
        'itens/<int:item_pk>/imagens/<int:imagem_pk>/padrao/',
        empresa_scoped(item_views.item_imagem_definir_padrao),
        name='item_imagem_definir_padrao',
    ),
    path(
        'itens/<int:pk>/etiqueta/pdf/',
        empresa_scoped(item_views.imprimir_etiqueta_item),
        name='imprimir_etiqueta_item',
    ),
    path(
        'itens/<int:pk>/etiqueta/png/',
        empresa_scoped(item_views.imprimir_etiqueta_item_png),
        name='imprimir_etiqueta_item_png',
    ),
    path(
        'itens/<int:pk>/',
        empresa_scoped(item_views.detalhes_item),
        name='detalhes_item',
    ),
    path(
        'itens/<int:pk>/editar/',
        empresa_scoped(item_views.item_editar),
        name='item_editar',
    ),
    path(
        'itens/<int:pk>/excluir/',
        empresa_scoped(item_views.item_excluir),
        name='item_excluir',
    ),
]
