# Generated by Django 6.0.3 on 2026-03-27 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_empresa_cor_tema'),
        ('rh', '0010_remove_valetransporte_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mês')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('titulo', models.CharField(blank=True, max_length=30, verbose_name='Título')),
                ('fechada', models.BooleanField(default=False, verbose_name='Fechada')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias_rh', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Competência',
                'verbose_name_plural': 'Competências',
                'ordering': ['-ano', '-mes', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ValeTransporteTabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da tabela')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('fechada', models.BooleanField(default=False, verbose_name='Fechada')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabelas_vt', to='controles_rh.competencia')),
            ],
            options={
                'verbose_name': 'Tabela de Vale Transporte',
                'verbose_name_plural': 'Tabelas de Vale Transporte',
                'ordering': ['ordem', 'nome', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ValeTransporteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150, verbose_name='Nome')),
                ('funcao', models.CharField(blank=True, max_length=120, verbose_name='Função')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('valor_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor a pagar')),
                ('pix', models.CharField(blank=True, max_length=150, verbose_name='Chave Pix')),
                ('tipo_pix', models.CharField(blank=True, choices=[('cpf', 'CPF'), ('telefone', 'Telefone'), ('email', 'E-mail'), ('aleatoria', 'Chave aleatória')], max_length=20, verbose_name='Tipo Pix')),
                ('banco', models.CharField(blank=True, max_length=120, verbose_name='Banco')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_vale_transporte', to='rh.funcionario')),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='controles_rh.valetransportetabela')),
            ],
            options={
                'verbose_name': 'Item de Vale Transporte',
                'verbose_name_plural': 'Itens de Vale Transporte',
                'ordering': ['ordem', 'nome', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='competencia',
            constraint=models.UniqueConstraint(fields=('empresa', 'mes', 'ano'), name='unique_competencia_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='valetransportetabela',
            constraint=models.UniqueConstraint(fields=('competencia', 'nome'), name='unique_tabela_vt_por_competencia'),
        ),
    ]
