# Generated by Django 6.0.3 on 2026-03-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controles_rh', '0001_initial'),
        ('empresas', '0002_empresa_cor_tema'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competencia',
            unique_together={('empresa', 'ano', 'mes')},
        ),
    ]
