# Generated by Django 6.0.3 on 2026-06-29 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles_rh', '0018_anexodiversocompetencia'),
        ('rh', '0020_curriculo_cat_cnh_curriculo_funcoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alteracaofolhalinha',
            name='premio',
        ),
        migrations.CreateModel(
            name='PremiacaoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premio_atual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prêmio atual (R$)')),
                ('premio_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prêmio anterior (R$)')),
                ('media_premiacao', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Média premiação (R$)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premiacoes_funcionarios', to='controles_rh.competencia')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premiacoes_folha', to='rh.funcionario')),
            ],
            options={
                'verbose_name': 'Premiação de funcionário',
                'verbose_name_plural': 'Premiações de funcionários',
                'ordering': ['funcionario__nome', 'id'],
                'constraints': [models.UniqueConstraint(fields=('competencia', 'funcionario'), name='unique_premiacao_por_competencia_funcionario')],
            },
        ),
    ]
