# Generated by Django 6.0.3 on 2026-07-06 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles_rh', '0019_remove_alteracaofolhalinha_premio_and_more'),
        ('rh', '0020_curriculo_cat_cnh_curriculo_funcoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoSalarioControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_empresa', models.CharField(blank=True, max_length=120, verbose_name='Banco Empresa')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('competencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento_salario_controle', to='controles_rh.competencia')),
            ],
            options={
                'verbose_name': 'Pagamento de salário (geração)',
                'verbose_name_plural': 'Pagamentos de salário (gerações)',
            },
        ),
        migrations.CreateModel(
            name='PagamentoSalarioLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='controles_rh.pagamentosalariocontrole')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_salario', to='rh.funcionario')),
            ],
            options={
                'verbose_name': 'Linha de pagamento de salário',
                'verbose_name_plural': 'Linhas de pagamento de salário',
                'ordering': ['funcionario__nome', 'id'],
                'constraints': [models.UniqueConstraint(fields=('controle', 'funcionario'), name='unique_pagamento_salario_por_controle_funcionario')],
            },
        ),
    ]
