# Generated by Django 6.0.3 on 2026-07-06 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles_rh', '0020_pagamentosalariocontrole_pagamentosalariolinha'),
        ('financeiro', '0025_alter_pagamentobancarioavulso_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamentosalariocontrole',
            name='banco_empresa',
        ),
        migrations.AddField(
            model_name='pagamentosalariocontrole',
            name='conta_bancaria_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_salario_controles', to='financeiro.contabancaria', verbose_name='Banco Empresa'),
        ),
    ]
