# Generated by Django 6.0.3 on 2026-07-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles_rh', '0022_remove_pagamentosalariocontrole_conta_bancaria_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentosalariocontrole',
            name='nome',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nome'),
        ),
    ]
