# Generated by Django 6.0.3 on 2026-07-06 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles_rh', '0023_pagamentosalariocontrole_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleCompetenciaOrdem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, verbose_name='Chave do controle')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_controles', to='controles_rh.competencia')),
            ],
            options={
                'verbose_name': 'Ordem de controle da competência',
                'verbose_name_plural': 'Ordens de controles da competência',
                'ordering': ['ordem', 'id'],
                'constraints': [models.UniqueConstraint(fields=('competencia', 'chave'), name='unique_ordem_controle_por_competencia')],
            },
        ),
    ]
