# Generated by Django 6.0.3 on 2026-07-06 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles_rh', '0024_controlecompetenciaordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentosalariocontrole',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_salario_controles', to='controles_rh.competencia'),
        ),
    ]
