# Generated by Django 6.0.3 on 2026-07-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles_rh', '0025_alter_pagamentosalariocontrole_competencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cestabasicaitem',
            name='lotacao',
            field=models.CharField(blank=True, max_length=120, verbose_name='Local de Trabalho'),
        ),
    ]
