# Generated by Django 6.0.3 on 2026-07-21 18:37

import django.db.models.deletion
from django.db import migrations, models


def migrar_pagamentos_vt_existentes(apps, schema_editor):
    ValeTransporteItem = apps.get_model('controles_rh', 'ValeTransporteItem')
    ValeTransportePagamento = apps.get_model('controles_rh', 'ValeTransportePagamento')
    itens = ValeTransporteItem.objects.filter(valor_pago__gt=0)
    pagamentos = []
    for item in itens.iterator():
        pagamentos.append(
            ValeTransportePagamento(
                item_id=item.pk,
                valor=item.valor_pago,
                data_pagamento=item.data_pagamento,
                observacao=(item.observacao or '')[:255],
                ordem=1,
            )
        )
    if pagamentos:
        ValeTransportePagamento.objects.bulk_create(pagamentos, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('controles_rh', '0026_alter_cestabasicaitem_lotacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValeTransportePagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor pago')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de pagamento')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observacao')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='controles_rh.valetransporteitem')),
            ],
            options={
                'verbose_name': 'Pagamento de Vale Transporte',
                'verbose_name_plural': 'Pagamentos de Vale Transporte',
                'ordering': ['ordem', 'data_pagamento', 'id'],
            },
        ),
        migrations.RunPython(migrar_pagamentos_vt_existentes, migrations.RunPython.noop),
    ]
