# Generated by Django 6.0.3 on 2026-03-10 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_empresa_cor_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('codigo', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_erp', models.PositiveIntegerField(blank=True, help_text='Código interno/legado do ERP', null=True)),
                ('matricula', models.CharField(max_length=30, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='funcionarios/fotos/')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('cnh', models.CharField(blank=True, max_length=20)),
                ('categoria_cnh', models.CharField(blank=True, max_length=10)),
                ('nacionalidade', models.CharField(blank=True, max_length=60)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('endereco_completo', models.CharField(blank=True, max_length=255)),
                ('telefone_1', models.CharField(blank=True, max_length=20)),
                ('telefone_2', models.CharField(blank=True, max_length=20)),
                ('estado_civil', models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União estável')], max_length=20)),
                ('nome_mae', models.CharField(blank=True, max_length=200)),
                ('nome_pai', models.CharField(blank=True, max_length=200)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('inicio_prorrogacao', models.DateField(blank=True, null=True)),
                ('fim_prorrogacao', models.DateField(blank=True, null=True)),
                ('situacao_atual', models.CharField(choices=[('admitido', 'Admitido'), ('ativo', 'Ativo'), ('afastado', 'Afastado'), ('ferias', 'Férias'), ('demitido', 'Demitido')], default='admitido', max_length=20)),
                ('inicio_afastamento', models.DateField(blank=True, null=True)),
                ('fim_afastamento', models.DateField(blank=True, null=True)),
                ('data_demissao', models.DateField(blank=True, null=True)),
                ('tipo_demissao', models.CharField(blank=True, choices=[('', '---------'), ('sem_justa_causa', 'Sem justa causa'), ('com_justa_causa', 'Com justa causa'), ('pedido_demissao', 'Pedido de demissão'), ('termino_contrato', 'Término de contrato'), ('acordo', 'Acordo'), ('aposentadoria', 'Aposentadoria'), ('obito', 'Óbito'), ('outro', 'Outro')], max_length=30)),
                ('salario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adicional', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('data_ultimo_exame', models.DateField(blank=True, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=150)),
                ('agencia', models.CharField(blank=True, max_length=20)),
                ('tipo_conta', models.CharField(blank=True, choices=[('', '---------'), ('corrente', 'Conta Corrente'), ('poupanca', 'Conta Poupança'), ('salario', 'Conta Salário')], max_length=20)),
                ('operacao', models.CharField(blank=True, max_length=20)),
                ('numero_conta', models.CharField(blank=True, max_length=30)),
                ('tipo_pix', models.CharField(blank=True, choices=[('', '---------'), ('cpf', 'CPF'), ('email', 'E-mail'), ('telefone', 'Telefone'), ('aleatoria', 'Chave Aleatória')], max_length=20)),
                ('pix', models.CharField(blank=True, max_length=150)),
                ('e_social', models.CharField(blank=True, max_length=100)),
                ('analfabeto', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='rh.banco')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='rh.cargo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('parentesco', models.CharField(choices=[('filho', 'Filho(a)'), ('conjuge', 'Cônjuge'), ('enteado', 'Enteado(a)'), ('outro', 'Outro')], default='filho', max_length=20)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to='rh.funcionario')),
            ],
            options={
                'verbose_name': 'Dependente',
                'verbose_name_plural': 'Dependentes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotacoes', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Lotação',
                'verbose_name_plural': 'Lotações',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='funcionario',
            name='lotacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='rh.lotacao'),
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='funcionario',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='rh.setor'),
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_contrato', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Tipo de Contrato',
                'verbose_name_plural': 'Tipos de Contrato',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='rh.tipocontrato'),
        ),
    ]
