# Generated by Django 6.0.3 on 2026-03-10 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_alter_funcionario_cpf_alter_funcionario_matricula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='setor',
        ),
        migrations.DeleteModel(
            name='Setor',
        ),
    ]
