# Generated by Django 6.0.3 on 2026-03-11 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_remove_funcionario_setor_delete_setor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='fim_afastamento',
            new_name='data_fim_aviso',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='inicio_afastamento',
            new_name='data_inicio_aviso',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='id_erp',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='anexo_aviso',
            field=models.FileField(blank=True, null=True, upload_to='rh/avisos_demissao/'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='contribuinte_sindical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='observacoes_demissao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='pis',
            field=models.CharField(blank=True, max_length=20, verbose_name='PIS'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='precisa_exame_demissional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='recebe_vale_transporte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='rescisao_assinada',
            field=models.FileField(blank=True, null=True, upload_to='rh/rescisoes/'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo_aviso',
            field=models.CharField(blank=True, choices=[('', '---------'), ('trabalhado', 'Trabalhado'), ('indenizado', 'Indenizado'), ('dispensado', 'Dispensado do cumprimento')], max_length=20),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='valor_vale_transporte',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='adicional',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='AfastamentoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('doenca', 'Doença'), ('acidente_trabalho', 'Acidente de trabalho'), ('licenca_maternidade', 'Licença maternidade'), ('licenca_paternidade', 'Licença paternidade'), ('auxilio_doenca', 'Auxílio-doença'), ('suspensao', 'Suspensão'), ('outro', 'Outro')], max_length=30)),
                ('data_afastamento', models.DateField()),
                ('previsao_retorno', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afastamentos', to='rh.funcionario')),
            ],
            options={
                'verbose_name': 'Afastamento',
                'verbose_name_plural': 'Afastamentos',
                'ordering': ['-data_afastamento'],
            },
        ),
        migrations.CreateModel(
            name='ASOFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('admissional', 'Admissional'), ('periodico', 'Periódico'), ('demissional', 'Demissional'), ('retorno_trabalho', 'Retorno ao trabalho'), ('mudanca_funcao', 'Mudança de função'), ('outro', 'Outro')], max_length=30)),
                ('data', models.DateField()),
                ('anexo', models.FileField(blank=True, null=True, upload_to='rh/saude/aso/')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asos', to='rh.funcionario')),
            ],
            options={
                'verbose_name': 'ASO',
                'verbose_name_plural': 'ASOs',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='AtestadoLicencaFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('atestado_medico', 'Atestado médico'), ('licenca_medica', 'Licença médica'), ('licenca_maternidade', 'Licença maternidade'), ('licenca_paternidade', 'Licença paternidade'), ('licenca_nao_remunerada', 'Licença não remunerada'), ('outro', 'Outro')], max_length=30)),
                ('data', models.DateField()),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_fim', models.DateField(blank=True, null=True)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='rh/saude/atestados_licencas/')),
                ('observacoes', models.TextField(blank=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atestados_licencas', to='rh.funcionario')),
            ],
            options={
                'verbose_name': 'Atestado / Licença',
                'verbose_name_plural': 'Atestados / Licenças',
                'ordering': ['-data', '-periodo_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CertificadoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(max_length=120)),
                ('data', models.DateField(blank=True, null=True)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='rh/saude/certificados/')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='rh.funcionario')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-data', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='FeriasFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('periodo_aquisitivo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_aquisitivo_fim', models.DateField(blank=True, null=True)),
                ('gozo_inicio', models.DateField(blank=True, null=True)),
                ('gozo_fim', models.DateField(blank=True, null=True)),
                ('teve_abono_pecuniario', models.BooleanField(default=False)),
                ('dias_abono_pecuniario', models.PositiveIntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferias', to='rh.funcionario')),
            ],
            options={
                'verbose_name': 'Férias',
                'verbose_name_plural': 'Férias',
                'ordering': ['-gozo_inicio', '-periodo_aquisitivo_inicio'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaSaudeFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('acidente', 'Acidente'), ('doenca', 'Doença')], max_length=20)),
                ('descricao', models.TextField()),
                ('origem', models.CharField(blank=True, choices=[('trabalho', 'No trabalho'), ('percurso', 'No percurso'), ('outro', 'Outro')], max_length=20)),
                ('data', models.DateField(blank=True, null=True)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='rh/saude/ocorrencias/')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_saude', to='rh.funcionario')),
            ],
            options={
                'verbose_name': 'Ocorrência de Saúde',
                'verbose_name_plural': 'Ocorrências de Saúde',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PCMSOFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_vencimento', models.DateField()),
                ('anexo', models.FileField(blank=True, null=True, upload_to='rh/saude/pcmso/')),
                ('observacoes', models.TextField(blank=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcmso_registros', to='rh.funcionario')),
            ],
            options={
                'verbose_name': 'Registro de PCMSO',
                'verbose_name_plural': 'Registros de PCMSO',
                'ordering': ['-data_vencimento'],
            },
        ),
    ]
