# Generated by Django 6.0.3 on 2026-03-17 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_rename_fim_afastamento_funcionario_data_fim_aviso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='situacao_atual',
            field=models.CharField(choices=[('admitido', 'Admitido'), ('afastado', 'Afastado'), ('ferias', 'Férias'), ('demitido', 'Demitido'), ('inativo', 'Inativo'), ('terceirizado', 'Terceirizado'), ('outro', 'Outro')], default='admitido', max_length=20),
        ),
        migrations.CreateModel(
            name='AnexoAvulsoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=150)),
                ('data_documento', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('arquivo', models.FileField(upload_to='rh/anexos_avulsos/')),
                ('origem_label', models.CharField(default='Anexo avulso', editable=False, max_length=80)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_avulsos', to='rh.funcionario')),
            ],
            options={
                'verbose_name': 'Anexo avulso',
                'verbose_name_plural': 'Anexos avulsos',
                'ordering': ['-data_documento', '-criado_em'],
            },
        ),
    ]
