# Generated by Django 6.0.3 on 2026-03-25 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_cor_tema'),
        ('rh', '0006_historicoalteracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='LembreteRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=160)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('geral', 'Geral'), ('documento', 'Documento'), ('financeiro', 'Financeiro'), ('rh', 'RH'), ('saude', 'Saúde'), ('feriado', 'Feriado'), ('outro', 'Outro')], default='geral', max_length=20)),
                ('data', models.DateField()),
                ('cor', models.CharField(blank=True, default='', max_length=20)),
                ('concluido', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes_rh', to='empresas.empresa')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lembretes_rh', to='rh.funcionario')),
            ],
            options={
                'verbose_name': 'Lembrete RH',
                'verbose_name_plural': 'Lembretes RH',
                'ordering': ['data', 'titulo'],
            },
        ),
    ]
