# Generated by Django 6.0.3 on 2026-03-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_lembreterh'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='funcionario',
            name='unique_matricula_por_empresa',
        ),
        migrations.RemoveConstraint(
            model_name='funcionario',
            name='unique_cpf_por_empresa',
        ),
    ]
