# Generated by Django 6.0.3 on 2026-03-26 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_cor_tema'),
        ('rh', '0008_remove_funcionario_unique_matricula_por_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('vale_transporte', 'Vale Transporte')], max_length=40)),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, default='bi-grid', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_rh', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Controle RH',
                'verbose_name_plural': 'Controles RH',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='ValeTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('funcao', models.CharField(blank=True, max_length=120)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pix', models.CharField(blank=True, max_length=150)),
                ('banco', models.CharField(blank=True, max_length=120)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vales_transporte', to='empresas.empresa')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vales_transporte', to='rh.funcionario')),
            ],
            options={
                'verbose_name': 'Vale Transporte',
                'verbose_name_plural': 'Vales Transporte',
                'ordering': ['nome'],
            },
        ),
    ]
