# Generated by Django 6.0.3 on 2026-03-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0009_controlerh_valetransporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valetransporte',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='valetransporte',
            name='funcionario',
        ),
        migrations.DeleteModel(
            name='ControleRH',
        ),
        migrations.DeleteModel(
            name='ValeTransporte',
        ),
    ]
