# Generated by Django 6.0.3 on 2026-05-18 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_alter_empresa_endereco'),
        ('rh', '0016_funcionario_local_trabalho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(auto_now_add=True, db_index=True, verbose_name='Data')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('indicacao', models.CharField(blank=True, max_length=200, verbose_name='Indicação')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_analise', 'Em análise'), ('aprovado', 'Aprovado'), ('descartado', 'Descartado')], default='novo', max_length=20)),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculos', to='empresas.empresa')),
                ('funcao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculos', to='rh.cargo', verbose_name='Função')),
            ],
            options={
                'verbose_name': 'Currículo',
                'verbose_name_plural': 'Currículos',
                'ordering': ['-data', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='CurriculoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('arquivo', models.FileField(upload_to='rh/curriculos/anexos/')),
                ('descricao', models.CharField(blank=True, max_length=150)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='rh.curriculo')),
            ],
            options={
                'verbose_name': 'Anexo de currículo',
                'verbose_name_plural': 'Anexos de currículos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='curriculo',
            index=models.Index(fields=['empresa', 'data'], name='rh_curricul_empresa_7f3f56_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculo',
            index=models.Index(fields=['empresa', 'funcao'], name='rh_curricul_empresa_4cb705_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculo',
            index=models.Index(fields=['empresa', 'status'], name='rh_curricul_empresa_db49a3_idx'),
        ),
    ]
