# Generated by Django 6.0.3 on 2026-05-18 18:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0017_curriculo_curriculoanexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculo',
            name='data',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Data'),
        ),
    ]
