# Generated by Codex on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0018_alter_curriculo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='rh/curriculos/fotos/', verbose_name='Foto'),
        ),
    ]
