# Generated by Codex on 2026-05-20

from django.db import migrations, models


def copiar_funcao_para_funcoes(apps, schema_editor):
    Curriculo = apps.get_model('rh', 'Curriculo')
    for curriculo in Curriculo.objects.exclude(funcao_id__isnull=True).iterator():
        curriculo.funcoes.add(curriculo.funcao_id)


def remover_funcoes_migradas(apps, schema_editor):
    Curriculo = apps.get_model('rh', 'Curriculo')
    for curriculo in Curriculo.objects.all().iterator():
        curriculo.funcoes.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0019_curriculo_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculo',
            name='cat_cnh',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cat. CNH'),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='funcoes',
            field=models.ManyToManyField(blank=True, related_name='curriculos_multiplos', to='rh.cargo', verbose_name='Funções'),
        ),
        migrations.RunPython(copiar_funcao_para_funcoes, remover_funcoes_migradas),
    ]
