# Generated by Django 6.0.3 on 2026-07-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0020_curriculo_cat_cnh_curriculo_funcoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='tipo_cesta_basica',
            field=models.CharField(choices=[('nao', 'Não'), ('recebe', 'Recebe Cesta Básica'), ('refeitorio', 'Almoça no Refeitório')], default='recebe', max_length=20, verbose_name='Recebe cesta básica'),
        ),
    ]
