# Generated by Django 6.0.3 on 2026-08-04 17:04

import django.db.models.deletion
from django.db import migrations, models


def preencher_banco_empresa_pagamento(apps, schema_editor):
    Funcionario = apps.get_model('rh', 'Funcionario')
    PagamentoSalarioLinha = apps.get_model('controles_rh', 'PagamentoSalarioLinha')

    funcionario_ids_atualizados = set()
    linhas = (
        PagamentoSalarioLinha.objects.filter(conta_bancaria_empresa__isnull=False)
        .order_by(
            'funcionario_id',
            '-controle__competencia__ano',
            '-controle__competencia__mes',
            '-controle_id',
            '-id',
        )
        .values_list('funcionario_id', 'conta_bancaria_empresa_id')
    )
    for funcionario_id, conta_id in linhas:
        if funcionario_id in funcionario_ids_atualizados:
            continue
        Funcionario.objects.filter(pk=funcionario_id).update(banco_empresa_pagamento_id=conta_id)
        funcionario_ids_atualizados.add(funcionario_id)


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0026_alter_recebimentoavulso_status_and_more'),
        ('controles_rh', '0028_pagamentosalariolinha_ordem'),
        ('rh', '0021_funcionario_tipo_cesta_basica'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='banco_empresa_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios_pagamento_salario', to='financeiro.contabancaria', verbose_name='Banco Empresa para Pagamento'),
        ),
        migrations.RunPython(preencher_banco_empresa_pagamento, migrations.RunPython.noop),
    ]
