# Generated by Django 6.0.3 on 2026-05-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_alter_empresa_endereco'),
        ('fornecedores', '0001_initial'),
        ('rh', '0016_funcionario_local_trabalho'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fornecedor',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='fornecedor',
            constraint=models.UniqueConstraint(condition=models.Q(('cpf_cnpj__in', ['00000000000', '00000000000000']), _negated=True), fields=('empresa', 'cpf_cnpj'), name='fornecedor_doc_unico_exceto_zeros'),
        ),
    ]
