# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaautoadesiva',
            name='cor',
            field=models.CharField(default='#2563eb', max_length=7),
        ),
    ]
