# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_notaautoadesiva_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaautoadesiva',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='dashboard/notas_anexos/'),
        ),
    ]
