# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_notaautoadesiva_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaautoadesiva',
            name='cor',
            field=models.CharField(default='#facc15', max_length=7),
        ),
    ]
