# Generated by Codex on 2026-06-25

from django.conf import settings
from django.db import migrations, models


def copiar_responsavel_para_responsaveis(apps, schema_editor):
    NotaAutoadesiva = apps.get_model('dashboard', 'NotaAutoadesiva')
    through = NotaAutoadesiva.responsaveis.through
    registros = NotaAutoadesiva.objects.exclude(responsavel_id__isnull=True).values_list(
        'id',
        'responsavel_id',
    )
    for nota_id, responsavel_id in registros:
        through.objects.get_or_create(
            notaautoadesiva_id=nota_id,
            usuario_id=responsavel_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_notaautoadesiva_cor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notaautoadesiva',
            name='responsaveis',
            field=models.ManyToManyField(
                blank=True,
                related_name='notas_autoadesivas_recebidas_multiplas',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(copiar_responsavel_para_responsaveis, migrations.RunPython.noop),
    ]
