# Generated by Django 6.0.3 on 2026-07-14 18:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('empresas', '0005_alter_empresa_endereco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('descricao', models.TextField(blank=True)),
                ('modulo', models.CharField(choices=[('geral', 'Geral'), ('rh', 'RH'), ('financeiro', 'Financeiro'), ('estoque', 'Estoque'), ('obras', 'Obras'), ('clientes', 'Clientes'), ('fornecedores', 'Fornecedores'), ('local', 'Locais'), ('apontamento', 'Apontamento')], db_index=True, default='geral', max_length=30)),
                ('categoria', models.CharField(blank=True, help_text='Tipo interno: contrato_vencendo, conta_vencendo, exame_vencido etc.', max_length=80)),
                ('nivel', models.CharField(choices=[('info', 'Informativo'), ('atencao', 'Atenção'), ('urgente', 'Urgente')], db_index=True, default='atencao', max_length=20)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('lido', 'Lido'), ('resolvido', 'Resolvido'), ('ignorado', 'Ignorado')], db_index=True, default='aberto', max_length=20)),
                ('data_alerta', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('data_vencimento', models.DateField(blank=True, db_index=True, null=True)),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('chave', models.CharField(blank=True, help_text='Chave opcional para evitar duplicar alertas automáticos.', max_length=180)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('lido_em', models.DateTimeField(blank=True, null=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='empresas.empresa')),
                ('usuario', models.ForeignKey(blank=True, help_text='Vazio = alerta visível para todos os usuários da empresa.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-data_alerta', '-id'],
                'indexes': [models.Index(fields=['empresa', 'status', 'data_alerta'], name='alertas_ale_empresa_e97a3a_idx'), models.Index(fields=['empresa', 'modulo', 'status'], name='alertas_ale_empresa_9b8a13_idx'), models.Index(fields=['empresa', 'chave'], name='alertas_ale_empresa_68d6b2_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('chave', ''), _negated=True), fields=('empresa', 'chave'), name='alerta_empresa_chave_unica_quando_informada')],
            },
        ),
    ]
