# Generated by Django 6.0.3 on 2026-04-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_pagamento_nf_e_boletos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletopagamento',
            name='numero_doc',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Número doc'),
        ),
    ]
