# Generated by Django 6.0.3 on 2026-05-06 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_alter_empresa_endereco'),
        ('financeiro', '0015_pagamento_impostos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(help_text='Apelido para identificar a conta, ex.: Banco do Brasil principal.', max_length=160)),
                ('banco', models.CharField(max_length=120)),
                ('agencia', models.CharField(blank=True, max_length=30)),
                ('conta', models.CharField(max_length=40)),
                ('tipo_conta', models.CharField(choices=[('corrente', 'Conta Corrente'), ('poupanca', 'Conta Poupança'), ('salario', 'Conta Salário'), ('pagamento', 'Conta Pagamento'), ('outra', 'Outra')], default='corrente', max_length=20)),
                ('titular', models.CharField(blank=True, max_length=180)),
                ('documento', models.CharField(blank=True, max_length=18, verbose_name='CPF/CNPJ do titular')),
                ('pix', models.CharField(blank=True, max_length=180, verbose_name='Chave Pix')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_bancarias', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Conta bancária',
                'verbose_name_plural': 'Contas bancárias',
                'ordering': ['-ativo', 'banco', 'nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='contabancaria',
            constraint=models.UniqueConstraint(fields=('empresa', 'banco', 'agencia', 'conta'), name='financeiro_conta_bancaria_unica_por_empresa'),
        ),
    ]
