# Generated by Django 6.0.3 on 2026-05-06 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0016_contabancaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletopagamento',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, help_text='Em branco representa DINHEIRO.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boletos_pagos', to='financeiro.contabancaria', verbose_name='Pagamento realizado em'),
        ),
        migrations.AddField(
            model_name='pagamentoimposto',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, help_text='Em branco representa DINHEIRO.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_impostos', to='financeiro.contabancaria', verbose_name='Pagamento realizado em'),
        ),
        migrations.AddField(
            model_name='pagamentonotafiscalpagamento',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, help_text='Em branco representa DINHEIRO.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_nf_diretos', to='financeiro.contabancaria', verbose_name='Pagamento realizado em'),
        ),
        migrations.AddField(
            model_name='pagamentopessoal',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, help_text='Em branco representa DINHEIRO.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_pessoal', to='financeiro.contabancaria', verbose_name='Pagamento realizado em'),
        ),
    ]
