# Generated by Django 6.0.3 on 2026-05-06 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0017_rename_financeiro__empresa_16b4c2_idx_financeiro__empresa_776cfa_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recebimentoavulso',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, help_text='Em branco representa DINHEIRO.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_avulsos', to='financeiro.contabancaria', verbose_name='Recebimento realizado em'),
        ),
        migrations.AddField(
            model_name='recebimentomedicao',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, help_text='Em branco representa DINHEIRO.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_medicao', to='financeiro.contabancaria', verbose_name='Recebimento realizado em'),
        ),
    ]
