# Generated by Django 6.0.3 on 2026-05-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0024_pagamentopessoal_data_pagamento_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamentobancarioavulso',
            options={'ordering': ['-data_pagamento', '-pk'], 'verbose_name': 'Pagamento bancário avulso', 'verbose_name_plural': 'Pagamentos bancários avulsos'},
        ),
        migrations.RenameIndex(
            model_name='movimentocaixa',
            new_name='financeiro__empresa_776cfa_idx',
            old_name='financeiro__empresa_16b4c2_idx',
        ),
        migrations.RenameIndex(
            model_name='movimentocaixa',
            new_name='financeiro__caixa_i_d01e94_idx',
            old_name='financeiro__caixa_i_0b8b0f_idx',
        ),
        migrations.RenameIndex(
            model_name='pagamentobancarioavulso',
            new_name='financeiro__empresa_fc86d8_idx',
            old_name='fin_pagbacav_emp_data_idx',
        ),
        migrations.RenameIndex(
            model_name='pagamentonotafiscal',
            new_name='financeiro__empresa_98a8c9_idx',
            old_name='financeiro__empresa_5bfb85_idx',
        ),
        migrations.RenameIndex(
            model_name='pagamentonotafiscal',
            new_name='financeiro__empresa_d778c7_idx',
            old_name='financeiro__empresa_0e9a72_idx',
        ),
        migrations.AlterField(
            model_name='movimentocaixa',
            name='categoria_origem',
            field=models.CharField(choices=[('rec_avulso', 'Recebimento avulso'), ('rec_contrato', 'Recebimento (contrato)'), ('rec_medicao', 'Recebimento por medição'), ('pag_avulso', 'Pagamento avulso'), ('pag_vista', 'Pagamento à vista'), ('pag_boleto', 'Pagamento de boleto'), ('transf_caixa', 'Transferência entre caixas'), ('outro', 'Outro')], db_index=True, default='outro', help_text='Classificação do lançamento (recibo, contrato, boleto, etc.).', max_length=20, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='pagamentonotafiscal',
            name='descricao',
            field=models.CharField(blank=True, max_length=500, verbose_name='Descrição'),
        ),
    ]
