# Generated by Django 6.0.3 on 2026-08-03 13:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def criar_liquidacoes_recebimentos_existentes(apps, schema_editor):
    RecebimentoAvulso = apps.get_model('financeiro', 'RecebimentoAvulso')
    RecebimentoMedicao = apps.get_model('financeiro', 'RecebimentoMedicao')
    RecebimentoLiquidacao = apps.get_model('financeiro', 'RecebimentoLiquidacao')

    def migrar(modelo, campo_recebimento):
        for recebimento in modelo.objects.filter(status='pago').iterator(chunk_size=200):
            filtro = {campo_recebimento: recebimento}
            if RecebimentoLiquidacao.objects.filter(**filtro).exists():
                continue
            data_pagamento = recebimento.data_pagamento or recebimento.data
            if not data_pagamento and recebimento.criado_em:
                data_pagamento = recebimento.criado_em.date()
            if not data_pagamento:
                continue
            RecebimentoLiquidacao.objects.create(
                empresa_id=recebimento.empresa_id,
                movimento_id=recebimento.movimento_id,
                conta_bancaria_id=recebimento.conta_bancaria_id,
                data_pagamento=data_pagamento,
                valor=recebimento.valor,
                impostos=recebimento.impostos,
                valor_liquido=recebimento.valor_liquido,
                observacao=recebimento.observacao or '',
                **filtro,
            )

    migrar(RecebimentoAvulso, 'recebimento_avulso')
    migrar(RecebimentoMedicao, 'recebimento_medicao')


def remover_liquidacoes_recebimentos_existentes(apps, schema_editor):
    RecebimentoLiquidacao = apps.get_model('financeiro', 'RecebimentoLiquidacao')
    RecebimentoLiquidacao.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_alter_empresa_endereco'),
        ('financeiro', '0025_alter_pagamentobancarioavulso_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recebimentoavulso',
            name='status',
            field=models.CharField(choices=[('aberto', 'Em aberto'), ('parcial', 'Pago Parcial'), ('pago', 'Pago')], db_index=True, default='aberto', max_length=12),
        ),
        migrations.AlterField(
            model_name='recebimentomedicao',
            name='status',
            field=models.CharField(choices=[('aberto', 'Em aberto'), ('parcial', 'Pago Parcial'), ('pago', 'Pago')], db_index=True, default='aberto', max_length=12),
        ),
        migrations.CreateModel(
            name='RecebimentoLiquidacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_pagamento', models.DateField(db_index=True, verbose_name='Data de pagamento')),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('impostos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('observacao', models.TextField(blank=True)),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_liquidacoes', to='financeiro.contabancaria', verbose_name='Recebimento realizado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos_liquidacoes', to='empresas.empresa')),
                ('movimento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recebimento_liquidacao', to='financeiro.movimentocaixa')),
                ('recebimento_avulso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liquidacoes', to='financeiro.recebimentoavulso')),
                ('recebimento_medicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liquidacoes', to='financeiro.recebimentomedicao')),
            ],
            options={
                'verbose_name': 'Liquidação de recebimento',
                'verbose_name_plural': 'Liquidações de recebimentos',
                'ordering': ['data_pagamento', 'pk'],
                'indexes': [models.Index(fields=['empresa', 'data_pagamento'], name='financeiro__empresa_4665e2_idx'), models.Index(fields=['recebimento_avulso', 'data_pagamento'], name='financeiro__recebim_40f25a_idx'), models.Index(fields=['recebimento_medicao', 'data_pagamento'], name='financeiro__recebim_db7a01_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('recebimento_avulso__isnull', False), ('recebimento_medicao__isnull', True)), models.Q(('recebimento_avulso__isnull', True), ('recebimento_medicao__isnull', False)), _connector='OR'), name='financeiro_liquidacao_um_recebimento')],
            },
        ),
        migrations.RunPython(
            criar_liquidacoes_recebimentos_existentes,
            remover_liquidacoes_recebimentos_existentes,
        ),
    ]
