from django.urls import path

from core.view_helpers import empresa_scoped

from . import views

app_name = 'financeiro'

urlpatterns = [
    path('', empresa_scoped(views.dashboard), name='dashboard'),
    path('relatorios/', empresa_scoped(views.relatorios), name='relatorios'),
    path('buscar/', empresa_scoped(views.buscar_pagamentos), name='buscar_pagamentos'),
    path(
        'buscar/exportar/pdf/',
        empresa_scoped(views.buscar_pagamentos_pdf),
        name='buscar_pagamentos_pdf',
    ),
    path(
        'buscar/exportar/xlsx/',
        empresa_scoped(views.buscar_pagamentos_xlsx),
        name='buscar_pagamentos_xlsx',
    ),
    path(
        'partial/dashboard-cards/',
        empresa_scoped(views.partial_dashboard_cards),
        name='partial_dashboard_cards',
    ),
    path('caixas/', empresa_scoped(views.caixa_lista), name='caixa_lista'),
    path('caixas/novo/', empresa_scoped(views.caixa_novo), name='caixa_novo'),
    path('caixas/unificado/', empresa_scoped(views.caixa_unificado), name='caixa_unificado'),
    path(
        'caixas/unificado/extrato/pdf/',
        empresa_scoped(views.caixa_unificado_pdf),
        name='caixa_unificado_pdf',
    ),
    path('caixas/<int:pk>/', empresa_scoped(views.caixa_detalhe), name='caixa_detalhe'),
    path(
        'caixas/<int:pk>/extrato/pdf/',
        empresa_scoped(views.caixa_extrato_pdf),
        name='caixa_extrato_pdf',
    ),
    path(
        'caixas/<int:pk>/editar/',
        empresa_scoped(views.caixa_editar),
        name='caixa_editar',
    ),
    path(
        'caixas/<int:pk>/inativar/',
        empresa_scoped(views.caixa_inativar),
        name='caixa_inativar',
    ),
    path(
        'caixas/<int:pk>/reativar/',
        empresa_scoped(views.caixa_reativar),
        name='caixa_reativar',
    ),
    path(
        'movimentar/',
        empresa_scoped(views.movimentar_caixa),
        name='movimentar_caixa',
    ),
    path(
        'movimentar/recebimentos/<str:status>/pdf/',
        empresa_scoped(views.recebimentos_pdf),
        name='recebimentos_pdf',
    ),
    path(
        'movimentar/pagamento/',
        empresa_scoped(views.movimentar_pagamento),
        name='movimentar_pagamento',
    ),
    path(
        'pagamentos/bancario/',
        empresa_scoped(views.pagamento_bancario_lista),
        name='pagamento_bancario_lista',
    ),
    path(
        'pagamentos/bancario/novo/',
        empresa_scoped(views.pagamento_bancario_novo),
        name='pagamento_bancario_novo',
    ),
    path(
        'pagamentos/bancario/avulso/novo/',
        empresa_scoped(views.pagamento_bancario_avulso_novo),
        name='pagamento_bancario_avulso_novo',
    ),
    path(
        'pagamentos/bancario/avulso/<int:pk>/editar/',
        empresa_scoped(views.pagamento_bancario_avulso_editar),
        name='pagamento_bancario_avulso_editar',
    ),
    path(
        'pagamentos/bancario/<int:pk>/',
        empresa_scoped(views.pagamento_bancario_detalhe),
        name='pagamento_bancario_detalhe',
    ),
    path(
        'pagamentos/bancario/<int:pk>/editar/',
        empresa_scoped(views.pagamento_bancario_editar),
        name='pagamento_bancario_editar',
    ),
    path(
        'pagamentos/bancario/<int:pk>/excluir/',
        empresa_scoped(views.pagamento_bancario_excluir),
        name='pagamento_bancario_excluir',
    ),
    path(
        'pagamentos/bancario/parcelas/<int:pk>/pagar/',
        empresa_scoped(views.pagamento_bancario_pagar),
        name='pagamento_bancario_pagar',
    ),
    path(
        'pagamentos/bancario/parcelas/<int:pk>/estornar/',
        empresa_scoped(views.pagamento_bancario_parcela_estornar),
        name='pagamento_bancario_parcela_estornar',
    ),
    path(
        'pagamentos/bancario/parcelas/<int:pk>/valor/',
        empresa_scoped(views.pagamento_bancario_parcela_valor),
        name='pagamento_bancario_parcela_valor',
    ),
    path(
        'pagamentos/nf/novo/',
        empresa_scoped(views.pagamento_nf_novo),
        name='pagamento_nf_novo',
    ),
    path(
        'pagamentos/pessoal/novo/',
        empresa_scoped(views.pagamento_pessoal_novo),
        name='pagamento_pessoal_novo',
    ),
    path(
        'pagamentos/impostos/novo/',
        empresa_scoped(views.pagamento_imposto_novo),
        name='pagamento_imposto_novo',
    ),
    path(
        'pagamentos/impostos/<int:pk>/',
        empresa_scoped(views.pagamento_imposto_detalhe),
        name='pagamento_imposto_detalhe',
    ),
    path(
        'pagamentos/impostos/<int:pk>/editar/',
        empresa_scoped(views.pagamento_imposto_editar),
        name='pagamento_imposto_editar',
    ),
    path(
        'pagamentos/impostos/<int:pk>/excluir/',
        empresa_scoped(views.pagamento_imposto_excluir),
        name='pagamento_imposto_excluir',
    ),
    path(
        'pagamentos/pessoal/<int:pk>/',
        empresa_scoped(views.pagamento_pessoal_detalhe),
        name='pagamento_pessoal_detalhe',
    ),
    path(
        'pagamentos/pessoal/<int:pk>/editar/',
        empresa_scoped(views.pagamento_pessoal_editar),
        name='pagamento_pessoal_editar',
    ),
    path(
        'pagamentos/pessoal/<int:pk>/excluir/',
        empresa_scoped(views.pagamento_pessoal_excluir),
        name='pagamento_pessoal_excluir',
    ),
    path(
        'pagamentos/nf/<int:pk>/',
        empresa_scoped(views.pagamento_nf_detalhe),
        name='pagamento_nf_detalhe',
    ),
    path(
        'pagamentos/nf/fornecedor-info/',
        empresa_scoped(views.pagamento_nf_fornecedor_info),
        name='pagamento_nf_fornecedor_info',
    ),
    path(
        'pagamentos/nf/<int:pk>/editar/',
        empresa_scoped(views.pagamento_nf_editar),
        name='pagamento_nf_editar',
    ),
    path(
        'pagamentos/nf/<int:pk>/pagar-boleto/',
        empresa_scoped(views.pagamento_nf_pagar_boleto),
        name='pagamento_nf_pagar_boleto',
    ),
    path(
        'pagamentos/nf/<int:pk>/excluir/',
        empresa_scoped(views.pagamento_nf_excluir),
        name='pagamento_nf_excluir',
    ),
    path(
        'movimentar/recebimento-avulso/',
        empresa_scoped(views.recebimento_avulso_novo),
        name='recebimento_avulso_novo',
    ),
    path(
        'movimentar/recebimento-medicao/',
        empresa_scoped(views.recebimento_medicao_novo),
        name='recebimento_medicao_novo',
    ),
    path(
        'movimentar/recebimentos/<str:tipo>/<int:pk>/liquidar/',
        empresa_scoped(views.recebimento_liquidar),
        name='recebimento_liquidar',
    ),
    path(
        'movimentar/recebimentos/<str:tipo>/<int:pk>/editar/',
        empresa_scoped(views.recebimento_editar),
        name='recebimento_editar',
    ),
    path('categorias/', empresa_scoped(views.categoria_lista), name='categoria_lista'),
    path('contas-bancarias/', empresa_scoped(views.conta_bancaria_lista), name='conta_bancaria_lista'),
    path('contas-bancarias/nova/', empresa_scoped(views.conta_bancaria_novo), name='conta_bancaria_novo'),
    path(
        'contas-bancarias/<int:pk>/editar/',
        empresa_scoped(views.conta_bancaria_editar),
        name='conta_bancaria_editar',
    ),
    path(
        'contas-bancarias/<int:pk>/excluir/',
        empresa_scoped(views.conta_bancaria_excluir),
        name='conta_bancaria_excluir',
    ),
    path('categorias/novo/', empresa_scoped(views.categoria_novo), name='categoria_novo'),
    path(
        'categorias/<int:pk>/editar/',
        empresa_scoped(views.categoria_editar),
        name='categoria_editar',
    ),
    path(
        'categorias/<int:pk>/inativar/',
        empresa_scoped(views.categoria_inativar),
        name='categoria_inativar',
    ),
    path(
        'categorias/<int:pk>/reativar/',
        empresa_scoped(views.categoria_reativar),
        name='categoria_reativar',
    ),
]
