# Generated by Django 6.0

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0004_empresa_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                (
                    'nome',
                    models.CharField(
                        help_text='Nome identificador (ex.: obra, filial, setor físico).',
                        max_length=150,
                        verbose_name='Local',
                    ),
                ),
                ('endereco', models.CharField(blank=True, max_length=500, verbose_name='Endereço')),
                (
                    'link_maps',
                    models.URLField(
                        blank=True,
                        help_text='URL do Google Maps ou outro serviço de localização.',
                        max_length=2000,
                        verbose_name='Link (mapas)',
                    ),
                ),
                (
                    'empresa',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='locais',
                        to='empresas.empresa',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'nome')},
            },
        ),
    ]
