# Generated by Django on 2026-04-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0002_local_latitude_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalTrabalhoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                (
                    'empresa',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='locais_trabalho_ativos',
                        to='empresas.empresa',
                    ),
                ),
                (
                    'local',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ativacoes_trabalho',
                        to='local.local',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Local de trabalho ativo',
                'verbose_name_plural': 'Locais de trabalho ativos',
                'ordering': ['local__nome', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='localtrabalhoativo',
            constraint=models.UniqueConstraint(
                fields=('empresa', 'local'),
                name='unique_local_trabalho_ativo_por_empresa',
            ),
        ),
    ]

