# Generated by Django on 2026-04-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0003_localtrabalhoativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='link_maps_embed',
            field=models.URLField(
                blank=True,
                help_text='Cole aqui o link do atributo src do iframe do Google Maps.',
                max_length=2000,
                verbose_name='Link embed (iframe)',
            ),
        ),
    ]

