# Generated by Django 6.0.3 on 2026-03-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cor_tema',
            field=models.CharField(default='#0d6efd', help_text='Cor em hexadecimal. Ex: #0d6efd', max_length=7),
        ),
    ]
