# Generated by Django 6.0.3 on 2026-04-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_empresa_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.CharField(blank=True, help_text='Exibido nos cabeçalhos de PDF (junto com CNPJ e telefone).', max_length=500, verbose_name='Endereço'),
        ),
    ]
